# Generated by Django 2.2.11 on 2020-03-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
