# Generated by Django 2.2.11 on 2020-03-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200307_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=256)),
                ('description', models.CharField(default=None, max_length=256)),
                ('social_links', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(default=None, max_length=256)),
                ('password', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Artist',
        ),
    ]
