# Generated by Django 2.2.11 on 2020-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200308_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='token',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='fan',
            name='token',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
