# Generated by Django 2.2.11 on 2020-03-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200309_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
