# Generated by Django 2.2.11 on 2020-03-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200309_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='token',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AlterField(
            model_name='fan',
            name='token',
            field=models.CharField(default=None, max_length=256),
        ),
    ]
