# Generated by Django 2.2.11 on 2020-03-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200309_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fan',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fan',
            name='password',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
