# Generated by Django 2.2.11 on 2020-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200310_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='photo',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
