# Generated by Django 2.2.11 on 2020-03-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200311_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.TextField(),
        ),
    ]
