# Generated by Django 2.2.11 on 2020-03-11 14:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200311_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 11, 14, 38, 22, 347359, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='release',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 3, 11, 14, 38, 26, 489981, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
